import org.example.backend.entities.LetterRule

val letterRules = listOf(
    LetterRule('A', 1),
    LetterRule('E', 1),
    LetterRule('I', 1),
    LetterRule('O', 1),
    LetterRule('U', 1),
    LetterRule('L', 1),
    LetterRule('N', 1),
    LetterRule('S', 1),
    LetterRule('T', 1),
    LetterRule('R', 1),
    LetterRule('D', 2),
    LetterRule('G', 2),
    LetterRule('B', 3),
    LetterRule('C', 3),
    LetterRule('M', 3),
    LetterRule('P', 3),
    LetterRule('F', 4),
    LetterRule('H', 4),
    LetterRule('V', 4),
    LetterRule('W', 4),
    LetterRule('Y', 4),
    LetterRule('K', 6),
    LetterRule('J', 8),
    LetterRule('X', 8),
    LetterRule('Q', 10),
    LetterRule('Z', 10)
)